SocialDashboard/config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  #Route for changing application language.
  get '/change_locale/:locale', to: 'languages#change_locale', as: :change_locale


  #Routes for filter controller.
  get '/filters/:id/edit', to: 'filters#edit', as: :edit_filter
  delete '/filters/:id', to: 'filters#destroy', as: :destroy_filter
  post '/filters', to: 'filters#create'
  put '/filters', to: 'filters#update'


  #Route for chart controller.
  post '/charts', to: 'charts#create'

end

SocialDashboard/app/models/country.rb
class Country

  attr_accessor(:name, :latitude, :longitude, :woeid)

  def initialize(name, latitude = nil, longitude = nil, woeid = nil)
    @name = name
    @latitude = latitude
    @longitude = longitude
    @woeid = woeid
  end
end

SocialDashboard/app/models/phrase.rb
class Phrase

  attr_accessor(:text, :frequency)

  def initialize(text, frequency)
    @text = text
    @frequency = frequency
  end
end

SocialDashboard/app/models/phrases_filter.rb
class PhrasesFilter

  attr_accessor(:language, :country_list, :start_date, :end_date, :type)

  def initialize(language, country_list, start_date, end_date, type)
    @language = language
    @country_list = country_list
    @start_date = start_date
    @end_date = end_date
    @type = type
  end
end

SocialDashboard/app/models/post.rb
class Post

  attr_accessor(:content, :creation_date, :score)

  def initialize(content, creation_date, score)
    @content = content
    @creation_date = creation_date
    @score = score
  end
end

SocialDashboard/app/models/sna_filter.rb
class SNAFilter

  attr_accessor(:social_network, :username, :depth_level, :type)

  def initialize(social_network, username, depth_level, type)
    @social_network = social_network
    @username = username
    @depth_level = depth_level
    @type = type
  end
end

SocialDashboard/app/models/user.rb
class User

  attr_accessor(:username, :image_url, :country)

  def initialize(username, image_url = nil)
    @username = username
    @image_url = image_url
  end
end

SocialDashboard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    if cookies[:SocialDashboard_locale] && I18n.available_locales.include?(cookies[:SocialDashboard_locale].to_sym)
      l = cookies[:SocialDashboard_locale].to_sym
    else
      l = I18n.default_locale
      cookies.permanent[:SocialDashboard_locale] = l
    end
    I18n.locale = l
  end

end

SocialDashboard/app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  before_action :set_chart_service, only: [:create]

  def create
    json_filter = cookies[params[:key]]
    filter = get_cookie_filter(json_filter,params[:type])
    render json: self.send("create_#{params[:type]}_chart", filter)
  end


  private

    def create_graph_chart(filter)
      @chart_service.get_graph(filter)
    end


    def create_trends_chart(filter)
      @chart_service.get_trends(filter)
    end


    def create_popular_terms_chart(filter)
      @chart_service.get_popular_terms(filter)

    end


    def set_chart_service
      @chart_service = ChartService.new
    end


    #Returns the filter object depending on the input type.
    def get_cookie_filter(json_filter, type)
      data = JSON.parse(json_filter)
      if type.eql?("trends") || type.eql?("popular_terms")
        filter = PhrasesFilter.new(data['language'], generate_country_list(data['country_list']), data['start_date'], data['end_date'],data['type'])
      else
        filter = SNAFilter.new(data['social_network'], data['username'], data['depth_level'],data['type'])
      end
    end


    #Creates an array of countrys using hash data.
    def generate_country_list(countries_hash)
      country_list = countries_hash.map { |c| Country.new(c['name'], c['latitude'], c['longitude'], c['woeid']) }
    end
end

SocialDashboard/app/controllers/filters_controller.rb
class FiltersController < ApplicationController

  before_action :set_filter_service, only: [:create, :update, :destroy, :edit]

  def edit
    key = params[:id].to_sym
    json_object = @filter_service.get_filter(key)
    render json: json_object
  end


  def create
     key = @filter_service.add_filter(set_filter)
    render json: key
  end


  def update
    @filter_service.update_filter(params[:filter_key], set_filter)
    render json: params[:filter_key]
  end


  def destroy
    key = params[:id].to_sym
    @filter_service.remove_filter(key)
    render json: key
  end

  private

    def set_filter_service
      cookie_accessor = CookieAccessor.new(cookies)
      @filter_service = FilterService.new(cookie_accessor)
    end


    def set_filter
      if params[:type].eql?('graph')
        filter = SNAFilter.new(params[:social_network], params[:user], params[:depth_level], params[:filter_type])
      else
        param_list = []
        country_list = params[:countries]
        country_list.each_value do |country|
          c = Country.new(country[:name], country[:location][:latitude].to_f, country[:location][:longitude].to_f, country[:location][:woeid].to_i)
          param_list.push(c)
        end
        filter = PhrasesFilter.new(params[:language], param_list, params[:start_time], params[:end_time], params[:filter_type])
      end
      filter
    end
end

SocialDashboard/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:SocialDashboard_locale] = l
    redirect_to request.referer || root_url
  end
end

SocialDashboard/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

SocialDashboard/app/helpers/application_helper.rb
module ApplicationHelper
end

SocialDashboard/app/helpers/chart_helper.rb
module ChartHelper
end

SocialDashboard/app/helpers/filter_helper.rb
module FilterHelper
end

SocialDashboard/app/views/filters/_add_phrase_chart.html.haml
/ Filter for popular terms and trends modal
#main-filters.modal.fade.modal-fmodal-filtersilters{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h3.modal-title
          = t('filters.title')
          %span.chart-type
      %div
        .container-fluid
          .row
            .col-md-12
              / Here was an h3 tag
              / tabs left
              .tabbable.tabs-left
                %ul.nav.nav-tabs
                  %li#li-region.active
                    %a#region-link{"data-toggle" => "tab", :href => "#region"}
                      %span#region-check.check-span.fa.fa-check-circle-o{"aria-hidden" => "true"}
                      .clear
                      = image_tag("icons/region.png", class: "img-responsive filter-image", alt: "Region icon")
                      %label.filter-label
                        = t('filters.phrases.region.tab-nm')
                  %li#li-time
                    %a#time-link{"data-toggle" => "tab", :href => "#time"}
                      %span#time-check.check-span.fa.fa-check-circle-o{"aria-hidden" => "true"}
                      .clear
                      = image_tag("icons/time.png", class: "img-responsive filter-image", alt: "Time icon")
                      %label.filter-label
                        = t('filters.phrases.time.tab-nm')
                  %li#li-language
                    %a#language-link{"data-toggle" => "tab", :href => "#language"}
                      %span#language-check.check-span.fa.fa-check-circle-o{"aria-hidden" => "true"}
                      .clear
                      = image_tag("icons/languages.jpg", class: "img-responsive filter-image", alt: "Languages icon")
                      %label.filter-label
                        = t('filters.phrases.lang.tab-nm')
                .tab-content



                  #region.tab-pane.active.region
                    .region-container
                      %button#region-btn-clear.btn.btn-sm.pull-right{:type => "button"}
                        = t('buttons.filters.clean')
                      %h4
                        = t('filters.phrases.region.title')
                      %hr
                      .region-select
                        %h5.region-label
                          = t('filters.phrases.region.dropdown-label')
                        .dropdown.region-dropdown
                          %button#dropdownMenu1.btn.btn-default.dropdown-toggle.drop-down-toggle-region{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
                            = t('filters.phrases.region.dropdown.title')
                            %span.caret
                          %ul.dropdown-menu.dropdown-menu-regions{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
                            %li.region-options{:role => "presentation", :value => "worldRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.ww')
                            %li.region-options{:role => "presentation", :value => "naRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.na')
                            %li.region-options{:role => "presentation", :value => "caRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.ca')
                            %li.region-options{:role => "presentation", :value => "saRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.sa')
                            %li.region-options{:role => "presentation", :value => "carRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.car')
                            %li.region-options{:role => "presentation", :value => "euwRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.euw')
                            %li.region-options{:role => "presentation", :value => "eueRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.eue')
                            %li.region-options{:role => "presentation", :value => "afRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.af')
                            %li.region-options{:role => "presentation", :value => "asRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.as')
                            %li.region-options{:role => "presentation", :value => "oceRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.oce')
                            %li.region-options{:role => "presentation", :value => "lataRegion"}
                              %a{:role => "menuitem", :tabindex => "-1"}
                                = t('filters.phrases.region.dropdown.lata')
                      .region-map-container
                        #vmap

                  #time.tab-pane.time
                    %button#time-btn-clear.btn.btn-sm.pull-right{:type => "button"}
                      = t('buttons.filters.clean')
                    %h4
                      = t('filters.phrases.time.title')
                    %hr
                      .filter-datepicker-containers
                        %div.row
                          %div.col-sm-8
                            %div.col-sm-6
                              %h5.font-bold
                                = t('filters.phrases.time.init')
                              .form-group
                                #start-timepicker1.input-group.date
                                  %input#start-timepicker2.form-control.time-input-picker{:type => "text"}/
                                  %span#start-timepicker3.input-group-addon
                                    %span.fa.fa-calendar
                            %div.col-sm-6
                              %h5.font-bold
                                = t('filters.phrases.time.fin')
                              .form-group
                                #finish-timepicker1.input-group.date
                                  %input#finish-timepicker2.form-control.time-input-picker{:type => "text"}/
                                  %span#finish-timepicker3.input-group-addon
                                    %span.fa.fa-calendar
                            .filter-time-resume
                            %hr
                            %hr
                              %h4
                                = t('filters.phrases.time.subtitle')
                              %br
                              .filter-time-resume-container.col-sm-10
                                .filter-date-summary-box
                                  %h6.font-bold
                                    = t('filters.phrases.time.years')
                                  #filter-resume-year
                                    / here goes the number corresponding to the year difference
                                    %span 0
                                .filter-date-summary-box
                                  %h6.font-bold
                                    = t('filters.phrases.time.months')
                                  #filter-resume-month
                                    / here goes the number corresponding to the year difference
                                    %span 0
                                .filter-date-summary-box
                                  %h6.font-bold
                                    = t('filters.phrases.time.days')
                                  #filter-resume-day
                                    / here goes the number corresponding to the days difference
                                    %span 0
                            .tab-footer
                  #language.tab-pane.language
                    %button#language-btn-clear.btn.btn-sm.pull-right.pull-bottom{:type => "button"}
                      = t('buttons.filters.clean')
                    %h4
                      = t('filters.phrases.lang.title')
                    %hr
                    .language-info-container
                      %div.row
                        %div.col-sm-10
                          %h5.font-bold
                            = t('filters.phrases.lang.input-label')
                          %form
                            .form-group
                              %input{"data-list" => "", class: "form-control", id: "language-input", placeholder: "#{t('filters.phrases.lang.input-placeholder')}"}
      / /tabs
      / /row
      .modal-footer
        %button#filters-btn-clear.btn{:type => "button"}
          = t('buttons.filters.clean-all')
        %button#phrases-filter-apply.btn.btn-success{:type => "button"}
          = t('buttons.apply')
          / Filter for popular terms and trends modal END

SocialDashboard/app/views/filters/_add_sna_chart.html.haml
/ Filter for data analysis modal
#data-analysis-filter.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h3#myModalLabel.modal-title
          = t('filters.title')
          %span.chart-type
      .modal-body
        %h4
          = t('filters.sna.sn')
        %form
          .row
            .col-sm-9
              .btn-group#social-network{"data-toggle" => "buttons"}
                %label.btn.btn-default.active#sna-twitter-label
                  %input#sna-twitter-button{:name => "quality[25]", :type => "radio", :value => "Twitter"}
                  Twitter
                %label.btn.btn-default#sna-kodu-label
                  %input#sna-kodu-button{:name => "quality[25]", :type => "radio", :value => "Kodu"}
                  Kodu
        %br
        %h4
          = t('filters.sna.user')
        %form
          .form-group
            %input.form-control#filter-user-input
        %br
        %h4
          = t('filters.sna.depth')
        %form
          .row
            .col-sm-9
              .btn-group#depth-level{"data-toggle" => "buttons"}
                %label.btn.btn-default.active
                  %input#q158{:name => "quality[25]", :type => "radio", :value => "1"}
                    1
                %label.btn.btn-default
                  %input#q159{:name => "quality[25]", :type => "radio", :value => "2"}
                    2
                %label.btn.btn-default
                  %input#q160{:name => "quality[25]", :type => "radio", :value => "3"}
                    3
                %label.btn.btn-default
                  %input#q161{:name => "quality[25]", :type => "radio", :value => "4"}
                    4
                %label.btn.btn-default
                  %input#q162{:name => "quality[25]", :type => "radio", :value => "5"}
                    5
      .modal-footer
        %button.btn.btn-success#sna-filter-apply{:type => "button"}
          = t('buttons.apply')
          / Filter for data analysis modal END

SocialDashboard/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SocialDashboard
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div#body-container
      %header
        %nav.navbar.navbar-static-top.navbar-default
          .container.navbar-container
            %h4.pull-left.navbar-logo
              %i.fa.fa-users
                SocialDashboard
      %main
        = render "partials/sidebar"
        = yield
        %div#modal-container
          %label#filter-key
          = render "filters/add_phrase_chart"
          = render "filters/add_sna_chart"
          #confirm.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog.modal-lg
              .modal-content
                .modal-header
                  %h4
                    = t('load-filters.question')
                  %br
                  %h5
                    = t('load-filters.content')
                .modal-footer
                  %button.btn.btn-primary#accept-filters{"data-dismiss" => "modal", :type => "button"}
                    = t('load-filters.opt-yes')
                  %button.btn#reject-filters{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    = t('load-filters.opt-no')

      %footer.footer
        %nav.navbar.navbar-default
          .container.navbar-container
            %h5.pull-right
              &copy;
              = t('footer.sign')
            %ul.nav.navbar-nav.navbar-left.dropup-navbar
              %li.dropdown.dropup
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = t('footer.languages.lang')
                  %span.caret
                %ul.dropdown-menu#languages-dropup{:role => "menu"}
                  %li
                    = link_to t('footer.languages.es'), change_locale_path(:es)
                  %li
                    = link_to t('footer.languages.en'), change_locale_path(:en)
                  %li
                    = link_to t('footer.languages.pt'), change_locale_path(:pt)


%script{:src => "/assets/mainEvents.js" }

SocialDashboard/app/views/pages/home.html.haml
.row
  #error-alert.alert.fade.in.alert-danger
    %div.close-alert{:type => "button"} ×
    %h3#alert-message
  %div#loadingDiv
  .clear
  #delete-all-charts
    = t('buttons.delete-filters')
    %i.fa.fa-trash-o
  .clear
  .container
    .col-md-10.col-md-offset-1#main-chart-col
      %style
        background-image:
      %div#main-chart{style: "background-image: url('#{image_path(t('footer.languages.current-lang'))}');"}

  .row#small-charts
    .container
      .col-md-3
        %div#div1.small-chart-div
      .col-md-3
        %div#div2.small-chart-div
      .col-md-3
        %div#div3.small-chart-div
      .col-md-3
        %div#div4.small-chart-div

SocialDashboard/app/views/partials/_graph.html.haml
.container.graph-container
  .graph-row
    .graph-columns
      .graph
        .control-zoom
          %a.control-zoom-in{:href => "#", :title => "Zoom in"}
          %a.control-zoom-out{:href => "#", :title => "Zoom out"}
        .node-info
          .close-button
          .node-link-container
            %a.node-link{:href => "#"}
          %textarea.node-description{:readonly => ""}

SocialDashboard/app/views/partials/_sidebar.html.haml
/ Sidebar
/ Sidebar Button
#sidebar
  .sidebar-button.shadowed.vcentered{:title => "#{t('sidebar.title')}"}
    #arrow-container
      %p#arrow-char ◂
  / Sidebar Options
  .sidebar.vcentered
    .sidebar-content.shadowed
      / Menu
      %ul
        %li.graph-type{:id => "popular_terms",:value => "popular_terms"}
          %a{:href => "#"}
            %i.fa.fa-plus-circle
            = t('charts.pt')
        %li.graph-type{:id => "trends",:value => "trends"}
          %a{:href => "#"}
            %i.fa.fa-plus-circle
            = t ('charts.tr')
        %li.graph-type{:id => "network",:value => "graph"}
          %a{:href => "#"}
            %i.fa.fa-plus-circle
            = t('charts.net')
        %li.graph-type{:id => "centrality",:value => "graph"}
          %a{:href => "#"}
            %i.fa.fa-plus-circle
            = t('charts.ct')
        %li.graph-type{:id => "density",:value => "graph"}
          %a{:href => "#"}
            %i.fa.fa-plus-circle
            = t('charts.ds')
        %li.graph-type{:id => "distance",:value => "graph"}
          %a{:href => "#"}
            %i.fa.fa-plus-circle
            = t('charts.dt')